// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Annotation
{
  public NsName getName () { return m_Name; }
  public void setName (NsName v) { m_Name = v; }
  public java.lang.String getValue () { return m_Value; }
  public void setValue (java.lang.String v) { m_Value = v; }
  
  private NsName m_Name;
  private java.lang.String m_Value;
}

