// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Annotated
{
  public Annotation [] getAnnotations () { return m_Annotations; }
  public boolean hasAnnotations () { return m_Annotations != null; }
  public void clearAnnotations () { m_Annotations = null; }
  public void setAnnotations (Annotation [] v) { m_Annotations = v; }
  
  private Annotation [] m_Annotations;
}

