// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Define extends Annotated
{
  public NsName getName () { return m_Name; }
  public void setName (NsName v) { m_Name = v; }
  public int getId () { return m_Id; }
  public boolean hasId () { return has_Id; }
  public void clearId () { has_Id = false; }
  public void setId (int v) { m_Id = v; has_Id = true; }
  public TypeDef getType () { return m_Type; }
  public void setType (TypeDef v) { m_Type = v; }
  
  private boolean has_Id;
  
  private NsName m_Name;
  private int m_Id;
  private TypeDef m_Type;
}

