// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Enum extends TypeDef
{
  public Symbol [] getSymbols () { return m_Symbols; }
  public void setSymbols (Symbol [] v) { m_Symbols = v; }
  
  private Symbol [] m_Symbols;
}

