// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Fixed extends TypeDef
{
  public int getSize () { return m_Size; }
  public void setSize (int v) { m_Size = v; }
  
  private int m_Size;
}

