// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class FixedDec extends TypeDef
{
  public byte getScale () { return m_Scale; }
  public void setScale (byte v) { m_Scale = v; }
  
  private byte m_Scale;
}

