// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class GroupDecl extends Annotated
{
  public NsName getName () { return m_Name; }
  public void setName (NsName v) { m_Name = v; }
  public long getId () { return m_Id; }
  public void setId (long v) { m_Id = v; }
  
  private NsName m_Name;
  private long m_Id;
}

