// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class GroupDef extends Annotated
{
  public NsName getName () { return m_Name; }
  public void setName (NsName v) { m_Name = v; }
  public long getId () { return m_Id; }
  public boolean hasId () { return has_Id; }
  public void clearId () { has_Id = false; }
  public void setId (long v) { m_Id = v; has_Id = true; }
  public FieldDef [] getFields () { return m_Fields; }
  public void setFields (FieldDef [] v) { m_Fields = v; }
  public NsName getSuper () { return m_Super; }
  public boolean hasSuper () { return m_Super != null; }
  public void clearSuper () { m_Super = null; }
  public void setSuper (NsName v) { m_Super = v; }
  
  private boolean has_Id;
  
  private NsName m_Name;
  private long m_Id;
  private FieldDef [] m_Fields;
  private NsName m_Super;
}

