// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class NsName
{
  public java.lang.String getNs () { return m_Ns; }
  public boolean hasNs () { return m_Ns != null; }
  public void clearNs () { m_Ns = null; }
  public void setNs (java.lang.String v) { m_Ns = v; }
  public java.lang.String getName () { return m_Name; }
  public void setName (java.lang.String v) { m_Name = v; }
  
  private java.lang.String m_Ns;
  private java.lang.String m_Name;
}

