// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Number extends TypeDef
{
  public int getMaxPrecision () { return m_MaxPrecision; }
  public boolean hasMaxPrecision () { return has_MaxPrecision; }
  public void clearMaxPrecision () { has_MaxPrecision = false; }
  public void setMaxPrecision (int v) { m_MaxPrecision = v; has_MaxPrecision = true; }
  
  private boolean has_MaxPrecision;
  
  private int m_MaxPrecision;
}

