// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Ref extends TypeDef
{
  public NsName getType () { return m_Type; }
  public void setType (NsName v) { m_Type = v; }
  
  private NsName m_Type;
}

