// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class SchemaAnnotation
{
  public Annotation [] getAnnotations () { return m_Annotations; }
  public void setAnnotations (Annotation [] v) { m_Annotations = v; }
  public java.lang.String getNs () { return m_Ns; }
  public boolean hasNs () { return m_Ns != null; }
  public void clearNs () { m_Ns = null; }
  public void setNs (java.lang.String v) { m_Ns = v; }
  
  private Annotation [] m_Annotations;
  private java.lang.String m_Ns;
}

