// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Sequence extends TypeDef
{
  public TypeDef getType () { return m_Type; }
  public void setType (TypeDef v) { m_Type = v; }
  
  private TypeDef m_Type;
}

