// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class String extends TypeDef
{
  public byte getMaxSize () { return m_MaxSize; }
  public boolean hasMaxSize () { return has_MaxSize; }
  public void clearMaxSize () { has_MaxSize = false; }
  public void setMaxSize (byte v) { m_MaxSize = v; has_MaxSize = true; }
  
  private boolean has_MaxSize;
  
  private byte m_MaxSize;
}

