// Generated by blinkc.js

package com.pantor.blink.msg.blink;

public class Symbol extends Annotated
{
  public java.lang.String getName () { return m_Name; }
  public void setName (java.lang.String v) { m_Name = v; }
  public int getValue () { return m_Value; }
  public void setValue (int v) { m_Value = v; }
  
  private java.lang.String m_Name;
  private int m_Value;
}

